server:
  gateway:
    host: 127.0.0.1
    port: 8080
  verifyRPC:
    host: 127.0.0.1
    port: 50051
  stateRPC:
    host: 127.0.0.1
    port: 50052
    rpcCount: 10
  mysql:
    host: 127.0.0.1
    port: 3309
    user: zorjen
    password: root
    schema: im
  redis:
    host: 127.0.0.1
    port: 6380
    password: root.
  kafka:
    broker: bootstrap.servers
    host: 127.0.0.1
    port: 9092
