server:
  state:
    host: 127.0.0.1
    port: 50052
  im:
    s1:
      name: hunan-im
      host: 0.0.0.0
      port: 8090
      rpcPort: 50055
      rpcCOunt: 2
      status: backup
    s2:
      name: beijing-im
      host: 127.0.0.1
      port: 8091
      rpcPort: 20001
      rpcCount: 2
      status: backup
    im-total: 2
  mysql:
    host: 127.0.0.1
    port: 33060
    user: zorjen
    password: root
    schema: chatServ
    clientCount: 2
    machineId: 1
  redis:
    host: 127.0.0.1
    port: 6380
    password: root
    clientCount: 2
    machineId: 1
  kafka:
    broker: bootstrap.servers
    host: 127.0.0.1
    port: 9092
