server:
  gateway:
    host: 127.0.0.1
    port: 8080
  verify:
    host: 127.0.0.1
    port: 50051
  state:
    host: 127.0.0.1
    port: 50052
  self:
    name : chatServer1
    host: 0.0.0.0
    port: 8090
    rpcPort: 50055
  peerServer:
    - chatServer1:
        host: 127.0.0.1
        port: 50056
    - chatServer2:
        host: 127.0.0.1
        port: 50057
  mysql:
    host: 127.0.0.1
    port: 3309
    user: zorjen
    password: root
    schema: im
  redis:
    host: 127.0.0.1
    port: 6380
    password: root.
